# Generated by Django 5.1.4 on 2024-12-21 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='admin_page.component')),
            ],
        ),
        migrations.CreateModel(
            name='Component_description_technique_paragraphe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_technique_paragraphes', to='admin_page.component')),
            ],
        ),
        migrations.CreateModel(
            name='Component_details_technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caractéristique', models.CharField(max_length=50)),
                ('valeur', models.CharField(max_length=50)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_technique', to='admin_page.component')),
            ],
        ),
        migrations.CreateModel(
            name='Component_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareil_documents', to='admin_page.component')),
            ],
        ),
        migrations.CreateModel(
            name='Component_model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model3D', models.FileField(upload_to='models3d/')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareil_models3d', to='admin_page.component')),
            ],
        ),
        migrations.CreateModel(
            name='Component_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareil_videos', to='admin_page.component')),
            ],
        ),
        migrations.CreateModel(
            name='paragraphe_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('paragraphe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphe_images', to='admin_page.component_description_technique_paragraphe')),
            ],
        ),
    ]
