# Generated by Django 5.1.4 on 2025-01-07 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_component_component_description_technique_paragraphe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_model3d',
            name='model3D',
            field=models.FileField(upload_to='models3d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'blend', 'fbx', 'obj'])]),
        ),
    ]
