# Generated by Django 5.1.4 on 2025-01-12 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0003_alter_component_model3d_model3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='component_images/')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_images', to='admin_page.component')),
            ],
        ),
    ]
